// Seed catalog. Realistic phase-1 content so the screen renders and is interactive without
// a database. Later this module maps Drizzle rows instead; nothing else changes.
import type { Product } from "./types";

export const STYLE_TAGS = ["קלאסי", "מודרני", "טרופי", "שחור-לבן", "כפרי", "זוהר", "רומנטי"];

let n = 0;
const id = () => `seed-${++n}`;

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: id(),
    name: "מפת שולחן קטיפה",
    category: "tablecloths",
    layer: "table",
    dimensions: { widthMm: 3200, depthMm: 3200, heightMm: 5 },
    categoryFields: {},
    spec: "בד קטיפה",
    unitPrice: 45,
    styleTags: ["קלאסי", "זוהר"],
    variants: [
      { id: id(), name: "זהב" },
      { id: id(), name: "שמנת" },
      { id: id(), name: "בורדו", unitPrice: 52 },
    ],
  },
  {
    id: id(),
    name: "כיסא נפוליאון",
    category: "chairs",
    layer: "floor",
    dimensions: { widthMm: 420, depthMm: 450, heightMm: 920 },
    categoryFields: {},
    spec: "נפוליאון, זהב",
    unitPrice: 28,
    styleTags: ["קלאסי"],
    variants: [
      { id: id(), name: "זהב" },
      { id: id(), name: "כסף" },
    ],
  },
  {
    id: id(),
    name: "כיסא שקוף",
    category: "chairs",
    layer: "floor",
    dimensions: { widthMm: 430, depthMm: 460, heightMm: 900 },
    categoryFields: {},
    spec: "פוליקרבונט שקוף",
    unitPrice: 32,
    styleTags: ["מודרני"],
    variants: [],
  },
  {
    id: id(),
    name: "שולחן עגול 1.8מ׳",
    category: "tables",
    layer: "floor",
    dimensions: { diameterMm: 1800, heightMm: 750 },
    categoryFields: { seats: 12 },
    unitPrice: 40,
    styleTags: ["קלאסי", "מודרני"],
    variants: [],
  },
  {
    id: id(),
    name: "שנדליר קריסטל",
    category: "chandeliers",
    layer: "ceiling",
    dimensions: { diameterMm: 800, heightMm: 1100 },
    categoryFields: { arms: 12 },
    unitPrice: 320,
    styleTags: ["זוהר", "קלאסי"],
    variants: [],
  },
  {
    id: id(),
    name: "פמוט זכוכית",
    category: "candlesticks",
    layer: "table",
    dimensions: { widthMm: 120, depthMm: 120, heightMm: 350 },
    categoryFields: { arms: 5 },
    unitPrice: 18,
    styleTags: ["רומנטי", "זוהר"],
    variants: [],
    appearance: { shape: "circle", content: "icon", icon: "flame" },
  },
  {
    id: id(),
    name: "שטיח פרחוני",
    category: "rugs",
    layer: "floor",
    dimensions: { widthMm: 3000, depthMm: 2000, heightMm: 12 },
    categoryFields: {},
    spec: "3×2 מ׳, גוון ירוק",
    unitPrice: 150,
    styleTags: ["טרופי", "כפרי"],
    variants: [],
  },
  {
    id: id(),
    name: "מרכז שולחן — סידור פרחים",
    category: "centerpieces",
    layer: "table",
    dimensions: { diameterMm: 400, heightMm: 550 },
    categoryFields: {},
    spec: "סידור גבוה",
    unitPrice: 65,
    styleTags: ["רומנטי", "טרופי"],
    variants: [
      { id: id(), name: "לבן" },
      { id: id(), name: "ורוד" },
    ],
  },
  {
    id: id(),
    name: "במה מודולרית",
    category: "stages",
    layer: "floor",
    dimensions: { widthMm: 1000, depthMm: 1000, heightMm: 400 },
    categoryFields: {},
    spec: "6 מודולים, 2 מדרגות",
    unitPrice: 220,
    styleTags: ["מודרני"],
    variants: [],
    appearance: {
      shape: "custom",
      content: "none",
      outline: [
        { x: 0, y: 0 }, { x: 3000, y: 0 }, { x: 3000, y: 1000 },
        { x: 1200, y: 1000 }, { x: 1200, y: 2000 }, { x: 0, y: 2000 },
      ],
    },
  },
  {
    id: id(),
    name: "בר עגול מואר",
    category: "bars",
    layer: "floor",
    dimensions: { diameterMm: 1200, heightMm: 1100 },
    categoryFields: {},
    spec: "עגול, תאורה פנימית",
    unitPrice: 200,
    styleTags: ["מודרני", "זוהר"],
    variants: [],
    appearance: { shape: "circle", content: "name" },
  },
  {
    id: id(),
    name: "ראנר טרופי",
    category: "tablecloths",
    layer: "table",
    dimensions: { widthMm: 2800, depthMm: 400, heightMm: 3 },
    categoryFields: {},
    spec: "פשתן",
    unitPrice: 22,
    styleTags: ["טרופי", "כפרי"],
    variants: [
      { id: id(), name: "עלים" },
      { id: id(), name: "מונסטרה" },
    ],
  },
  {
    id: id(),
    name: "כיסא חתן וכלה",
    category: "chairs",
    layer: "floor",
    dimensions: { widthMm: 520, depthMm: 520, heightMm: 1150 },
    categoryFields: {},
    spec: "שמנת",
    unitPrice: 90,
    styleTags: ["זוהר", "רומנטי"],
    variants: [],
  },

  // ברים ומזנונים (F-4.3 catalog groups) — the existing "בר עגול מואר" above plus the four
  // shapes/sizes a designer actually chooses between.
  {
    id: id(),
    name: "בר גדול",
    category: "bars",
    layer: "floor",
    dimensions: { widthMm: 900, depthMm: 650, heightMm: 1100 },
    categoryFields: {},
    spec: "מלבני, עמדת ברמן",
    unitPrice: 280,
    styleTags: ["מודרני"],
    variants: [],
  },
  {
    id: id(),
    name: "בר עגול 4.5",
    category: "bars",
    layer: "floor",
    dimensions: { diameterMm: 450, heightMm: 1100 },
    categoryFields: {},
    unitPrice: 180,
    styleTags: ["מודרני"],
    variants: [],
    appearance: { shape: "circle", content: "name" },
  },
  {
    id: id(),
    name: "בר חצי",
    category: "bars",
    layer: "floor",
    dimensions: { widthMm: 650, depthMm: 450, heightMm: 1100 },
    categoryFields: {},
    spec: "חצי־ירח",
    unitPrice: 220,
    styleTags: ["מודרני"],
    variants: [],
  },
  {
    id: id(),
    name: "בר עגול 650",
    category: "bars",
    layer: "floor",
    dimensions: { diameterMm: 650, heightMm: 1100 },
    categoryFields: {},
    unitPrice: 230,
    styleTags: ["מודרני", "זוהר"],
    variants: [],
    appearance: { shape: "circle", content: "name" },
  },

  // חופות — קטגוריה חדשה.
  {
    id: id(),
    name: "חופת יהלומים",
    category: "chuppahs",
    layer: "floor",
    dimensions: { widthMm: 2500, depthMm: 2500, heightMm: 2800 },
    categoryFields: {},
    spec: "מסגרת יהלומים, זכוכית/קריסטל",
    unitPrice: 950,
    styleTags: ["זוהר", "קלאסי"],
    variants: [],
  },
  {
    id: id(),
    name: "חופת אליפסה",
    category: "chuppahs",
    layer: "floor",
    dimensions: { widthMm: 2800, depthMm: 2000, heightMm: 2600 },
    categoryFields: {},
    spec: "מסגרת אליפסה",
    unitPrice: 880,
    styleTags: ["מודרני"],
    variants: [],
  },
  {
    id: id(),
    name: "חופת שקדיות",
    category: "chuppahs",
    layer: "floor",
    dimensions: { widthMm: 2400, depthMm: 2400, heightMm: 2500 },
    categoryFields: {},
    spec: "פרחי שקדיה",
    unitPrice: 820,
    styleTags: ["רומנטי", "כפרי"],
    variants: [],
  },

  // מוצרים נלווים — ווילונות/קשתות/עמודים, קטגוריות חדשות.
  {
    id: id(),
    name: "וילון קטיפה",
    category: "curtains",
    layer: "floor",
    dimensions: { widthMm: 3000, depthMm: 100, heightMm: 2800 },
    categoryFields: {},
    spec: "קטיפה כבדה, תלייה מרצפה לתקרה",
    unitPrice: 60,
    styleTags: ["קלאסי", "זוהר"],
    variants: [
      { id: id(), name: "שמנת" },
      { id: id(), name: "בורדו" },
    ],
  },
  {
    id: id(),
    name: "קשת פרחים",
    category: "arches",
    layer: "floor",
    dimensions: { widthMm: 2200, depthMm: 400, heightMm: 2500 },
    categoryFields: {},
    spec: "מסגרת מתכת עם עיטור פרחוני",
    unitPrice: 450,
    styleTags: ["רומנטי", "זוהר"],
    variants: [],
  },
  {
    id: id(),
    name: "עמוד יווני",
    category: "columns",
    layer: "floor",
    dimensions: { diameterMm: 300, heightMm: 1800 },
    categoryFields: {},
    unitPrice: 120,
    styleTags: ["קלאסי"],
    variants: [],
    appearance: { shape: "circle", content: "name" },
  },
];
